CREATE TABLE recipes(
  recipe_id SERIAL PRIMARY KEY,
  recipe_title varchar(255) NOT NULL,
  recipe_description varchar(255),
  recipe_preview varchar(255) NOT NULL,
  recipe_time integer NOT NULL,
  recipe_isVegan boolean NOT NULL,
  recipe_portions integer NOT NULL,
  recipe_isModerated boolean NOT NULL,
  recipe_previousRecipe integer
);

CREATE TABLE users(
  user_id uuid PRIMARY KEY DEFAULT
  uuid_generate_v4(),
  user_name varchar(255) NOT NULL,
  user_password varchar(255) NOT NULL,
  user_email varchar(255) NOT NULL,
  user_isAdmin boolean NOT NULL
);

INSERT INTO users (user_name, user_password, user_email, user_isAdmin) VALUES
('lada', '$2b$10$UEwa4Xt0ufSKOyhJ28Eorutc2y16Xw4QMfP9o1ChW58bLGvpJ.lfy', 'ladacherkasovav@yandex.ru', true);

CREATE TABLE favorites(
    favourite_id SERIAL PRIMARY KEY,
    user_id uuid REFERENCES users (user_id),
    recipe_id INTEGER REFERENCES recipes (recipe_id)
);

CREATE TABLE steps(
    step_id SERIAL PRIMARY KEY,
    step_text varchar(255) NOT NULL,
    step_image varchar(255) NOT NULL,
    recipe_id INTEGER REFERENCES recipes (recipe_id)
);

CREATE TABLE types(
  type_id SERIAL PRIMARY KEY,
  type_name varchar(255) NOT NULL
);

INSERT INTO types (type_name) VALUES
('Основные блюда'),
('Салаты'),
('Супы'),
('Закуски'),
('Соусы и заправки'),
('Выпечка и десерты'),
('Заготовки'),
('Напитки');

CREATE TABLE ingredients(
  ingredient_id SERIAL PRIMARY KEY,
  ingredient_name varchar(255) NOT NULL,
  ingredient_isModerated boolean
);

INSERT INTO ingredients (ingredient_name, ingredient_isModerated) VALUES
('Абрикос', false),
('Авокадо', false),
('Агар-агар', false),
('Аджика', false),
('Айва', false),
('Айран', false),
('Алоэ', false),
('Алыча', false),
('Ананас', false),
('Анис', false),
('Анчоусы', false),
('Апельсин', false),
('Арахис', false),
('Арбуз', false),
('Артишок', false),
('Ацидофилин', false),
('Багет', false),
('Бадьян', false),
('Базилик', false),
('Баклажан', false),
('Балык', false),
('Бальзам', false),
('Бальзамик', false),
('Бамия', false),
('Банан', false),
('Барабулька', false),
('Баранина', false),
('Баранка', false),
('Барбарис', false),
('Бастурма', false),
('Батат', false),
('Батон', false),
('Бедро куриное', false),
('Безе', false),
('Бекмес', false),
('Бекон', false),
('Белок яичный', false),
('Белорыбица', false),
('Бергамот', false),
('Бешамель', false),
('Биодобавка', false),
('Бисквит', false),
('Бобы', false),
('Ботва', false),
('Боярышник', false),
('Брокколи', false),
('Брусника', false),
('Брынза', false),
('Брюква', false),
('Бублик', false),
('Буженина', false),
('Булгур', false),
('Булка', false),
('Бульон', false),
('Валериана', false),
('Ванилин', false),
('Ваниль', false),
('Варенье', false),
('Васаби', false),
('Вафли', false),
('Вермишель', false),
('Ветчина', false),
('Вешенки', false),
('Взбитые сливки', false),
('Виноград', false),
('Вишня', false),
('Вода', false),
('Вода газированная', false),
('Вода минеральная', false),
('Водоросли', false),
('Галета', false),
('Гарам масала', false),
('Гвоздика', false),
('Глазурь', false),
('Глюкоза', false),
('Глютен', false),
('Говядина', false),
('Голень куриная', false),
('Голубика', false),
('Горбуша', false),
('Горошек зеленый', false),
('Горчица', false),
('Гранат', false),
('Гранола', false),
('Гребешок', false),
('Грейпфрут', false),
('Гренки', false),
('Гриб морской', false),
('Гриб чайный', false),
('Грибы', false),
('Грибы консервированные', false),
('Грудка', false),
('Грудка индюшки', false),
('Грудка куриная', false),
('Грудка утиная', false),
('Груша', false),
('Гуми', false),
('Гусь', false),
('Дайкон', false),
('Джем', false),
('Джем абрикосовый', false),
('Джем апельсиновый', false),
('Джусай', false),
('Дорадо', false),
('Драже', false),
('Дрожжи', false),
('Душица', false),
('Дыня', false),
('Ежевика', false),
('Ерш', false),
('Желатин', false),
('Желе', false),
('Желток яичный', false),
('Желудок', false),
('Желудь', false),
('Жимолость', false),
('Жмых овощной', false),
('Жмых фруктовый', false),
('Загуститель', false),
('Закваска', false),
('Заменитель сахара', false),
('Заменитель сухого молока', false),
('Зверобой', false),
('Зелень', false),
('Земляника', false),
('Зерно', false),
('Зефир', false),
('Зира', false),
('Зубатка', false),
('Иваси', false),
('Изюм', false),
('Икра красная', false),
('Икра минтая', false),
('Икра овощная', false),
('Икра рыбная', false),
('Икра черная', false),
('Имбирь', false),
('Индейка', false),
('Инжир', false),
('Ирга', false),
('Ириски', false),
('Йогурт', false),
('Кабачок', false),
('Какао сгущенное', false),
('Какао тертое', false),
('Какао-бобы', false),
('Какао-масло', false),
('Какао-порошок', false),
('Кактус', false),
('Калина', false),
('Калинджи', false),
('Кальмар', false),
('Камбала', false),
('Каперсы', false),
('Масло оливковое', false),
('Капуста белокочанная', false),
('Капуста брюссельская', false),
('Капуста квашеная', false),
('Капуста китайская', false),
('Капуста кольраби', false),
('Капуста краснокочанная', false),
('Капуста кудрявая', false),
('Капуста морская', false),
('Капуста пекинская', false),
('Капуста савойская', false),
('Капуста цветная', false),
('Капуста японская', false),
('Карамбола', false),
('Карамель', false),
('Карась', false),
('Карбонад', false),
('Кардамон', false),
('Каркаде', false),
('Карп', false),
('Карри', false),
('Картофель', false),
('Катык', false),
('Каштан', false),
('Квас', false),
('Кета', false),
('Кетчуп', false),
('Кефаль', false),
('Кефир', false),
('Киви', false),
('Кижуч', false),
('Кизил', false),
('Килька', false),
('Кинза', false),
('Киноа', false),
('Кисель', false),
('Кислота аскорбиновая', false),
('Кислота лимонная', false),
('Клементин', false),
('Клетчатка', false),
('Клубника', false),
('Клюква', false),
('Кокос', false),
('Колбаса', false),
('Конгрио', false),
('Конкилье', false),
('Конфитюр', false),
('Кора дуба', false),
('Корейка', false),
('Коренья', false),
('Корж', false),
('Кориандр', false),
('Корица', false),
('Корнишоны', false),
('Корюшка', false),
('Кофе', false),
('Краб', false),
('Крабовое мясо', false),
('Крабовые палочки', false),
('Крапива', false),
('Краситель пищевой', false),
('Крахмал', false),
('Крахмал картофельный', false),
('Крахмал кукурузный', false),
('Креветки', false),
('Крекер', false),
('Кресс-салат', false),
('Кролик', false),
('Крошка вафельная', false),
('Крошка хлебная', false),
('Крупа гречневая', false),
('Крупа кукурузная', false),
('Крупа манная', false),
('Крупа овсяная', false),
('Крупа перловая', false),
('Крупа пшеничная', false),
('Крупа ячневая', false),
('Крыжовник', false),
('Крылья куриные', false),
('Кукуруза', false),
('Кукурузные палочки', false),
('Кумин', false),
('Кумкват', false),
('Кунжут', false),
('Курага', false),
('Курица', false),
('Куркума', false),
('Кус-кус', false),
('Кэроб', false),
('Лаванда', false),
('Лаваш', false),
('Лайм', false),
('Лангуст', false),
('Лапша', false),
('Лед', false),
('Лен', false),
('Лепестки', false),
('Лепешка', false),
('Лечо', false),
('Ливер', false),
('Лимон', false),
('Лимонная трава', false),
('Лимонник', false),
('Лист виноградный', false),
('Лист вишневый', false),
('Лист древесный', false),
('Лист капустный', false),
('Лист лавровый', false),
('Лист малиновый', false),
('Лист смородиновый', false),
('Лист цветочный', false),
('Листья салата', false),
('Личи', false),
('Лобстер', false),
('Лосось', false),
('Лук белый', false),
('Лук зеленый', false),
('Лук красный', false),
('Лук репчатый', false),
('Лук-порей', false),
('Лук-шалот', false),
('Любисток', false),
('Майоран', false),
('Мак', false),
('Малина', false),
('Манго', false),
('Мангостин', false),
('Мандарин', false),
('Маракуйя', false),
('Маргарин', false),
('Мармелад', false),
('Марципан', false),
('Маршмеллоу', false),
('Маскарпоне', false),
('Маслины', false),
('Масло арахисовое', false),
('Масло виноградной косточки', false),
('Масло горчичное', false),
('Масло грецкого ореха', false),
('Масло кедрового ореха', false),
('Масло кокосовое', false),
('Масло кукурузное', false),
('Масло кунжутное', false),
('Масло льняное', false),
('Масло миндальное', false),
('Масло мятное', false),
('Масло пальмовое', false),
('Масло подсолнечное', false),
('Масло рапсовое', false),
('Масло растительное', false),
('Масло сливочное', false),
('Масло соевое', false),
('Масло топленое', false),
('Масло тыквенное', false),
('Масло хлопковое', false),
('Масло чесночное', false),
('Масло шоколадное', false),
('Маслята', false),
('Матча', false),
('Маш', false),
('Мед', false),
('Мелисса', false),
('Мидии', false),
('Миндаль', false),
('Минеола', false),
('Минтай', false),
('Можжевельник', false),
('Мойва', false),
('Моллюски', false),
('Молоко', false),
('Молоко кедровое', false),
('Молоко кокосовое', false),
('Молоко концентрированное', false),
('Молоко миндальное', false),
('Молоко сгущенное', false),
('Молоко соевое', false),
('Молоко сухое', false),
('Молоко топленое', false),
('Момордика', false),
('Морепродукты', false),
('Морковь', false),
('Мороженое', false),
('Морошка', false),
('Морской язык', false),
('Моцарелла', false),
('Мука амарантовая', false),
('Мука блинная', false),
('Мука гороховая', false),
('Мука гречневая', false),
('Мука кокосовая', false),
('Мука конопляная', false),
('Мука кукурузная', false),
('Мука кунжутная', false),
('Мука льняная', false),
('Мука миндальная', false),
('Мука нутовая', false),
('Мука овсяная', false),
('Мука полбяная', false),
('Мука пшеничная', false),
('Мука ржаная', false),
('Мука рисовая', false),
('Мука соевая', false),
('Мука специальная', false),
('Мука цельнозерновая', false),
('Мука черемуховая', false),
('Мука ячменная', false),
('Мюсли', false),
('Мясо', false),
('Мясо соевое', false),
('Мята', false),
('Навага', false),
('Налим', false),
('Наршараб', false),
('Нектар', false),
('Нектарин', false),
('Нори', false),
('Нуга', false),
('Нут', false),
('Облепиха', false),
('Овес', false),
('Огурец', false),
('Огурец маринованный', false),
('Огурец соленый', false),
('Окара', false),
('Окорок', false),
('Окунь', false),
('Окунь морской', false),
('Оленина', false),
('Оливки зеленые', false),
('Оливки черные', false),
('Опара', false),
('Опята', false),
('Орегано', false),
('Орех макадамия', false),
('Орех мускатный', false),
('Орехи', false),
('Орехи бразильские', false),
('Орехи грецкие', false),
('Орехи кедровые', false),
('Орехи кешью', false),
('Орехи лесные', false),
('Орехи пекан', false),
('Осьминог', false),
('Отруби', false),
('Пажитник', false),
('Палтус', false),
('Пангасиус', false),
('Панир', false),
('Папайя', false),
('Папоротник', false),
('Паприка сладкая', false),
('Пармезан', false),
('Паста арахисовая', false),
('Паста карри', false),
('Паста кунжутная', false),
('Паста ореховая', false),
('Паста перечная', false),
('Паста сахарная', false),
('Паста тахинная', false),
('Паста чесночно-имбирная', false),
('Пастернак', false),
('Пастила', false),
('Патиссон', false),
('Патока', false),
('Пахта', false),
('Пектин', false),
('Пеленгас', false),
('Перепел', false),
('Перец белый', false),
('Перец болгарский', false),
('Перец душистый', false),
('Перец зеленый', false),
('Перец кайен', false),
('Перец красный жгучий', false),
('Перец лимонный', false),
('Перец пепперони', false),
('Перец розовый', false),
('Перец сладкий', false),
('Перец сладкий желтый', false),
('Перец сладкий зеленый', false),
('Перец сладкий красный', false),
('Перец сычуаньский', false),
('Перец черный', false),
('Перец чили', false),
('Перец ямайский', false),
('Персик', false),
('Песто', false),
('Петрушка', false),
('Печень баранья', false),
('Печень говяжья', false),
('Печень гусиная', false),
('Печень индюшиная', false),
('Печень кролика', false),
('Печень куриная', false),
('Печень минтая', false),
('Печень свиная', false),
('Печень трески', false),
('Печень утиная', false),
('Питахайя', false),
('Пищевая добавка', false),
('Побеги', false),
('Полба', false),
('Помело', false),
('Померанец', false),
('Помидор', false),
('Помидор маринованный', false),
('Помидор соленый', false),
('Помидоры черри', false),
('Попкорн', false),
('Порошок горчичный', false),
('Порошок грибной', false),
('Порошок луковый', false),
('Порошок пекарский', false),
('Порошок томатный', false),
('Порошок чесночный', false),
('Портулак', false),
('Посыпка кондитерская', false),
('Простокваша', false),
('Пряности', false),
('Псиллиум', false),
('Путассу', false),
('Пшеница', false),
('Пшено', false),
('Пыльца цветочная', false),
('Пюре картофельное', false),
('Пюре овощное', false),
('Пюре томатное', false),
('Пюре фруктовое', false),
('Пюре ягодное', false),
('Разрыхлитель теста', false),
('Раки', false),
('Раковые шейки', false),
('Рамбутан', false),
('Рапаны', false),
('Рассол', false),
('Ребра', false),
('Ребра говяжьи', false),
('Ребра свиные', false),
('Ревень', false),
('Редис', false),
('Редька', false),
('Репа', false),
('Рикотта', false),
('Рис', false),
('Рис воздушный', false),
('Рис дикий', false),
('Рис коричневый', false),
('Розмарин', false),
('Романо', false),
('Ростки', false),
('Руккола', false),
('Рыба', false),
('Рябина красная', false),
('Рябина черноплодная', false),
('Ряженка', false),
('Саго', false),
('Сайда', false),
('Сайра', false),
('Салака', false),
('Сало', false),
('Салями', false),
('Сахар', false),
('Сахар коричневый', false),
('Сахар кусковой', false),
('Сахар тростниковый', false),
('Сахар-рафинад', false),
('Сахарная пудра', false),
('Свекла', false),
('Свекла листовая', false),
('Свинина', false),
('Свити', false),
('Сельдерей корневой', false),
('Сельдерей листовой', false),
('Сельдерей черешковый', false),
('Сельдь', false),
('Семга', false),
('Семена', false),
('Семена горчицы', false),
('Семена льна', false),
('Семена укропа', false),
('Семена чиа', false),
('Семечки', false),
('Семечки подсолнуха', false),
('Семечки тыквенные', false),
('Семолина', false),
('Сибас', false),
('Скумбрия', false),
('Слива', false),
('Сливки', false),
('Сливки кокосовые', false),
('Смалец', false),
('Сметана', false),
('Смородина белая', false),
('Смородина красная', false),
('Смородина черная', false),
('Сода', false),
('Соевые проростки', false),
('Соевый соус', false),
('Сок апельсиновый', false),
('Сок березовый', false),
('Сок гранатовый', false),
('Сок лимонный', false),
('Сок мандариновый', false),
('Сок морковный', false),
('Сок томатный', false),
('Сок яблочный', false),
('Сок ягодный', false),
('Солод', false),
('Соль', false),
('Соль нитритная', false),
('Соя', false),
('Спагетти', false),
('Спаржа', false),
('Спаржа соевая', false),
('Спирт', false),
('Ставрида', false),
('Стевия', false),
('Стрелки чесночные', false),
('Стружка кокосовая', false),
('Стружка шоколадная', false),
('Сумах', false),
('Сунели', false),
('Сухари', false),
('Сухари панировочные', false),
('Сыворотка', false),
('Сыр адыгейский', false),
('Сыр голландский', false),
('Сыр голубой', false),
('Сыр козий', false),
('Сыр колбасный', false),
('Сыр копченый', false),
('Сыр мягкий', false),
('Сыр плавленый', false),
('Сыр полутвердый', false),
('Сыр сливочный', false),
('Сыр сулугуни', false),
('Сыр твердый', false),
('Сыр творожный', false),
('Табаско', false),
('Тапиока', false),
('Тарталетка', false),
('Тархун', false),
('Творог', false),
('Творожная масса', false),
('Телятина', false),
('Тесто дрожжевое', false),
('Тесто заварное', false),
('Тесто песочное', false),
('Тесто пресное', false),
('Тесто слоеное', false),
('Тесто слоеное бездрожжевое', false),
('Тесто слоеное дрожжевое', false),
('Тесто фило', false),
('Тимьян', false),
('Ткемали', false),
('Тмин', false),
('Толокно', false),
('Томатная паста', false),
('Томаты вяленые', false),
('Томаты пассерованные', false),
('Томаты протертые', false),
('Томаты сушеные', false),
('Топинамбур', false),
('Тофу', false),
('Треска', false),
('Трюфель', false),
('Тунец', false),
('Тыква', false),
('Угорь', false),
('Удон', false),
('Укроп', false),
('Уксус', false),
('Улитки', false),
('Унаби', false),
('Урбеч', false),
('Урюк', false),
('Устрицы', false),
('Утка', false),
('Уцхо-сунели', false),
('Фарш индюшачий', false),
('Фарш куриный', false),
('Фарш мясной', false),
('Фарш рыбный', false),
('Фарш соевый', false),
('Фасоль', false),
('Фасоль консервированная', false),
('Фасоль стручковая', false),
('Фейхоа', false),
('Фенхель', false),
('Фета', false),
('Физалис', false),
('Филе куриное', false),
('Филе рыбное', false),
('Финик', false),
('Фисташки', false),
('Форель', false),
('Фосфат пищевой', false),
('Фризе', false),
('Фруктоза', false),
('Фундук', false),
('Фунчоза', false),
('Халва', false),
('Халва подсолнечная', false),
('Хамса', false),
('Хвоя', false),
('Хек', false),
('Хлеб', false),
('Хлебцы', false),
('Хлопья гороховые', false),
('Хлопья гречневые', false),
('Хлопья злаковые', false),
('Хлопья картофельные', false),
('Хлопья кукурузные', false),
('Хлопья овсяные', false),
('Хлопья панировочные', false),
('Хлопья пшенные', false),
('Хлопья рисовые', false),
('Хлопья шоколадные', false),
('Хлопья ячменные', false),
('Хлорид кальция', false),
('Хмели-сунели', false),
('Хмель', false),
('Хрен', false),
('Хурма', false),
('Цветки', false),
('Цедра апельсина', false),
('Цедра грейпфрута', false),
('Цедра лайма', false),
('Цедра лимона', false),
('Цедра мандарина', false),
('Цесарка', false),
('Цикорий', false),
('Цукаты', false),
('Цуккини', false),
('Цыпленок', false),
('Чабер', false),
('Чабрец', false),
('Чай белый', false),
('Чай зеленый', false),
('Чай красный', false),
('Чай черный', false),
('Черемуха', false),
('Черемша', false),
('Черешня', false),
('Черника', false),
('Чернослив', false),
('Чеснок', false),
('Чечевица', false),
('Шалфей', false),
('Шампиньоны', false),
('Шафран', false),
('Шейка куриная', false),
('Шейка свиная', false),
('Шелковица', false),
('Шелуха луковая', false),
('Шиповник', false),
('Шишки сосновые', false),
('Шнитт-лук', false),
('Шоколад белый', false),
('Шоколад молочный', false),
('Шоколад темный', false),
('Шпинат', false),
('Щавель', false),
('Щука', false),
('Эстрагон', false),
('Яблоко', false),
('Ягода', false),
('Язык говяжий', false),
('Язык свиной', false),
('Яйцо куриное', false),
('Яйцо перепелиное', false),
('Ямс', false),
('Ячмень', false),
('Молоко кунжутное', false),
('Солод ячменный', false),
('Морская соль', false),
('Сахар кокосовый', false),
('Сухой чеснок', false)

CREATE TABLE recipe_type(
    type_id integer REFERENCES types (type_id),
    recipe_id INTEGER REFERENCES recipes (recipe_id)
);

CREATE TABLE recipe_ingredient(
    ingredient_id integer REFERENCES ingredients (ingredient_id),
    recipe_id INTEGER REFERENCES recipes (recipe_id),
    recipe_ingredient_amount varchar(255) NOT NULL
);

--DELETE from recipe_type WHERE recipe_id = 63;
--DELETE from recipe_ingredient WHERE recipe_id = 63;
--DELETE from steps WHERE recipe_id = 63;
--DELETE from favorites WHERE recipe_id = 63;
--DELETE from recipes WHERE recipe_id = 63;
